In [62]:
import numpy as np
from scipy import io


In [63]:
D = io.loadmat('M1_M2_2m.mat')

In [64]:
for i in range(7):
    print(np.real(D['M1'][i]))

[ 1.  1.  1.  1.  2.  2.  2.  2.]
[ 1.  1.  2.  2.  1.  1.  2.  2.]
[ 1.  2.  1.  2.  1.  2.  1.  2.]
[ 1.  2.  2.  1.  2.  1.  1.  2.]
[  2.06770933e+10   2.06699583e+10   3.59252323e+06   3.59252323e+06
   3.59252323e+06   3.59252323e+06   2.06699583e+10   2.06772751e+10]
[  2.06770933e+10   3.59252323e+06   3.59252323e+06   2.06699583e+10
   2.06699583e+10   3.59252323e+06   3.59252323e+06   2.06772751e+10]
[ 1.  2.  3.  4.  3.  4.  1.  2.]


In [65]:
M1 = np.real(D['M1'])


In [61]:
len(M2[1,:])

4

In [59]:
%timeit M1[0,0]

84.2 ns ± 0.962 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [60]:
%timeit int(M1[0,0])

192 ns ± 3.85 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [58]:
M2

array([[1, 2, 1, 2],
       [1, 2, 2, 1]], dtype=uint8)

In [29]:
M2_ = np.copy(M2[0,:])

In [30]:
%timeit M2_[0]

74.1 ns ± 0.379 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [25]:
t = tuple(M2)[0]

In [26]:
t

array([1, 2, 1, 2], dtype=uint8)

In [27]:
%timeit t[0]

72.6 ns ± 1.16 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
